refs #91: create `CFGIgnoringAssert` to let specific detector to ignore assert
but this approach failed due to AnalysisCache problem:
that cache expect that we have only one CFG for each descriptor
so this branch has failed tests like below:

```
  Error pruning normal return edges for unconditionally throwing methods for UselessCode.method(I)V
    edu.umd.cs.findbugs.ba.DataflowAnalysisException: not enough values on stack: access=1, avail=0
      At edu.umd.cs.findbugs.ba.Frame.getStackValue(Frame.java:247)
```